// SPDX-License-Identifier: Apache-2.0
// Bundle reviewed real recordings; this command never invokes a model.
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import {mergePiTraces} from '../packages/pi-tracing/extensions/pi-tracing/merge.ts';
import {resolve} from 'node:path';

await mkdir('artifacts/examples', {recursive: true});
await rm('artifacts/examples/agentprof-example.tar', {force: true});
for (const [directory, output, module, constant] of [
  ['pi-opus-5', 'agentprof-example', 'example_trace', 'EXAMPLE_TRACE_BASE64'],
  ['pi-codemode', 'agentprof-codemode-example'],
  ['harness-comparison', 'agentprof-comparison-example', 'comparison_example_trace', 'COMPARISON_EXAMPLE_TRACE_BASE64'],
  ['claude-coding', 'agentprof-claude-example', 'claude_example_trace', 'CLAUDE_EXAMPLE_TRACE_BASE64'],
  ['codex-coding', 'agentprof-codex-example', 'codex_example_trace', 'CODEX_EXAMPLE_TRACE_BASE64'],
  ['muse-coding', 'agentprof-muse-example', 'muse_example_trace', 'MUSE_EXAMPLE_TRACE_BASE64'],
]) {
  const source = resolve(`examples/${directory}`);
  const manifest = JSON.parse(await readFile(resolve(source, 'recording.json'), 'utf8'));
  // Reviewed combined recordings already have unique packet sequence IDs and
  // retain each harness's clock snapshots. Copy them without Pi clock rewriting.
  const bytes = manifest.bundledFile ? await readFile(resolve(source, manifest.bundledFile))
    : mergePiTraces(await Promise.all(manifest.bundledFiles.map(async (file: string) =>
      ({bytes: await readFile(resolve(source, file))})))).bytes;
  await writeFile(`artifacts/examples/${output}.pftrace`, bytes);
  if (module) await writeFile(`third_party/overlays/perfetto/ui/src/plugins/dev.agentprof.Agentprof/${module}.ts`,
    '// SPDX-License-Identifier: Apache-2.0\n' +
    `// Generated by npm run trace:example from the real recordings in examples/${directory}.\n` +
    `export const ${constant} = '${bytes.toString('base64')}';\n`);
  console.log(`Bundled examples/${directory} in ${output}.pftrace (${bytes.length} bytes)`);
}
