// SPDX-License-Identifier: Apache-2.0
// Bundle reviewed real recordings; this command never invokes a model.
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import {mergePiTraces} from '../packages/pi-tracing/extensions/pi-tracing/merge.ts';
import {resolve} from 'node:path';

await mkdir('artifacts/examples', {recursive: true});
await rm('artifacts/examples/agentprof-example.tar', {force: true});
for (const [directory, output, module, constant] of [
  ['pi-opus-5', 'agentprof-example', 'example_trace', 'EXAMPLE_TRACE_BASE64'],
  ['pi-codemode', 'agentprof-codemode-example', 'codemode_example_trace', 'CODEMODE_EXAMPLE_TRACE_BASE64'],
]) {
  const source = resolve(`examples/${directory}`);
  const manifest = JSON.parse(await readFile(resolve(source, 'recording.json'), 'utf8'));
  const inputs = await Promise.all(manifest.bundledFiles.map(async (file: string) =>
    ({bytes: await readFile(resolve(source, file))})));
  const {bytes} = mergePiTraces(inputs);
  await writeFile(`artifacts/examples/${output}.pftrace`, bytes);
  await writeFile(`third_party/overlays/perfetto/ui/src/plugins/dev.agentprof.Agentprof/${module}.ts`,
    '// SPDX-License-Identifier: Apache-2.0\n' +
    `// Generated by npm run trace:example from the real Pi recordings in examples/${directory}.\n` +
    `export const ${constant} = '${bytes.toString('base64')}';\n`);
  console.log(`Bundled ${manifest.bundledFiles.length} real Pi processes in ${output}.pftrace (${bytes.length} bytes)`);
}
